### ISSUE TITLE
make error on freebsd 10.3

### ISSUE THREAD

**Issue by zhou0** [leapcode/bitmask-dev#6]
[venv] [lzhou@pcbsd-7076] ~/github.com/leapcode/bitmask-dev/archive/bitmask-dev-0.10a1% make dev-all
pip install -e '.[all]'
Obtaining file:///usr/home/lzhou/github.com/leapcode/bitmask-dev/archive/bitmask-dev-0.10a1
Requirement already satisfied: twisted>=14.0.0 in ./venv/lib/python2.7/site-packages (from leap.bitmask==0.10a1)
Requirement already satisfied: zope.interface in ./venv/lib/python2.7/site-packages (from leap.bitmask==0.10a1)
Requirement already satisfied: service-identity in ./venv/lib/python2.7/site-packages (from leap.bitmask==0.10a1)
Requirement already satisfied: colorama in ./venv/lib/python2.7/site-packages (from leap.bitmask==0.10a1)
Requirement already satisfied: srp in ./venv/lib/python2.7/site-packages (from leap.bitmask==0.10a1)
Requirement already satisfied: python-daemon in ./venv/lib/python2.7/site-packages (from leap.bitmask==0.10a1)
Requirement already satisfied: leap.common in ./venv/lib/python2.7/site-packages (from leap.bitmask==0.10a1)
Requirement already satisfied: leap.soledad.client in ./venv/lib/python2.7/site-packages (from leap.bitmask==0.10a1)
Requirement already satisfied: gnupg in ./venv/lib/python2.7/site-packages (from leap.bitmask==0.10a1)
Requirement already satisfied: vext.pyqt5 in ./venv/lib/python2.7/site-packages/vext.pyqt5-0.5.21-py2.7.egg (from leap.bitmask==0.10a1)
Collecting leap.bitmask_js (from leap.bitmask==0.10a1)
  Using cached leap.bitmask_js-0.1.201705221350.tar.gz
Requirement already satisfied: constantly>=15.1 in ./venv/lib/python2.7/site-packages (from twisted>=14.0.0->leap.bitmask==0.10a1)
Requirement already satisfied: hyperlink>=17.1.1 in ./venv/lib/python2.7/site-packages (from twisted>=14.0.0->leap.bitmask==0.10a1)
Requirement already satisfied: Automat>=0.3.0 in ./venv/lib/python2.7/site-packages (from twisted>=14.0.0->leap.bitmask==0.10a1)
Requirement already satisfied: incremental>=16.10.1 in ./venv/lib/python2.7/site-packages (from twisted>=14.0.0->leap.bitmask==0.10a1)
Requirement already satisfied: setuptools in ./venv/lib/python2.7/site-packages (from zope.interface->leap.bitmask==0.10a1)
Requirement already satisfied: pyasn1-modules in ./venv/lib/python2.7/site-packages (from service-identity->leap.bitmask==0.10a1)
Requirement already satisfied: attrs in ./venv/lib/python2.7/site-packages (from service-identity->leap.bitmask==0.10a1)
Requirement already satisfied: pyasn1 in ./venv/lib/python2.7/site-packages (from service-identity->leap.bitmask==0.10a1)
Requirement already satisfied: pyopenssl>=0.12 in ./venv/lib/python2.7/site-packages (from service-identity->leap.bitmask==0.10a1)
Requirement already satisfied: six in ./venv/lib/python2.7/site-packages (from srp->leap.bitmask==0.10a1)
Requirement already satisfied: lockfile>=0.10 in ./venv/lib/python2.7/site-packages (from python-daemon->leap.bitmask==0.10a1)
Requirement already satisfied: docutils in ./venv/lib/python2.7/site-packages (from python-daemon->leap.bitmask==0.10a1)
Requirement already satisfied: python-dateutil in ./venv/lib/python2.7/site-packages (from leap.common->leap.bitmask==0.10a1)
Requirement already satisfied: pyzmq>=14.4.1 in ./venv/lib/python2.7/site-packages (from leap.common->leap.bitmask==0.10a1)
Requirement already satisfied: jsonschema in ./venv/lib/python2.7/site-packages (from leap.common->leap.bitmask==0.10a1)
Requirement already satisfied: txzmq>=0.7.3 in ./venv/lib/python2.7/site-packages (from leap.common->leap.bitmask==0.10a1)
Requirement already satisfied: treq in ./venv/lib/python2.7/site-packages (from leap.soledad.client->leap.bitmask==0.10a1)
Requirement already satisfied: cryptography in ./venv/lib/python2.7/site-packages (from leap.soledad.client->leap.bitmask==0.10a1)
Requirement already satisfied: zope.proxy in ./venv/lib/python2.7/site-packages (from leap.soledad.client->leap.bitmask==0.10a1)
Requirement already satisfied: scrypt in ./venv/lib/python2.7/site-packages (from leap.soledad.client->leap.bitmask==0.10a1)
Requirement already satisfied: pysqlcipher in ./venv/lib/python2.7/site-packages (from leap.soledad.client->leap.bitmask==0.10a1)
Requirement already satisfied: leap.soledad.common in ./venv/lib/python2.7/site-packages (from leap.soledad.client->leap.bitmask==0.10a1)
Requirement already satisfied: psutil>=1.2.1 in ./venv/lib/python2.7/site-packages (from gnupg->leap.bitmask==0.10a1)
Requirement already satisfied: vext>=0.5.21 in ./venv/lib/python2.7/site-packages (from vext.pyqt5->leap.bitmask==0.10a1)
Requirement already satisfied: functools32; python_version == "2.7" in ./venv/lib/python2.7/site-packages (from jsonschema->leap.common->leap.bitmask==0.10a1)
Requirement already satisfied: requests>=2.1.0 in ./venv/lib/python2.7/site-packages (from treq->leap.soledad.client->leap.bitmask==0.10a1)
Requirement already satisfied: ipaddress in ./venv/lib/python2.7/site-packages (from cryptography->leap.soledad.client->leap.bitmask==0.10a1)
Requirement already satisfied: asn1crypto>=0.21.0 in ./venv/lib/python2.7/site-packages (from cryptography->leap.soledad.client->leap.bitmask==0.10a1)
Requirement already satisfied: enum34 in ./venv/lib/python2.7/site-packages (from cryptography->leap.soledad.client->leap.bitmask==0.10a1)
Requirement already satisfied: idna>=2.1 in ./venv/lib/python2.7/site-packages (from cryptography->leap.soledad.client->leap.bitmask==0.10a1)
Requirement already satisfied: cffi>=1.7 in ./venv/lib/python2.7/site-packages (from cryptography->leap.soledad.client->leap.bitmask==0.10a1)
Requirement already satisfied: routes in ./venv/lib/python2.7/site-packages (from leap.soledad.common->leap.soledad.client->leap.bitmask==0.10a1)
Requirement already satisfied: paste in ./venv/lib/python2.7/site-packages (from leap.soledad.common->leap.soledad.client->leap.bitmask==0.10a1)
Requirement already satisfied: ruamel.yaml>=0.11.10 in ./venv/lib/python2.7/site-packages (from vext>=0.5.21->vext.pyqt5->leap.bitmask==0.10a1)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python2.7/site-packages (from requests>=2.1.0->treq->leap.soledad.client->leap.bitmask==0.10a1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./venv/lib/python2.7/site-packages (from requests>=2.1.0->treq->leap.soledad.client->leap.bitmask==0.10a1)
Requirement already satisfied: urllib3<1.22,>=1.21.1 in ./venv/lib/python2.7/site-packages (from requests>=2.1.0->treq->leap.soledad.client->leap.bitmask==0.10a1)
Requirement already satisfied: pycparser in ./venv/lib/python2.7/site-packages (from cffi>=1.7->cryptography->leap.soledad.client->leap.bitmask==0.10a1)
Requirement already satisfied: repoze.lru>=0.3 in ./venv/lib/python2.7/site-packages (from routes->leap.soledad.common->leap.soledad.client->leap.bitmask==0.10a1)
Requirement already satisfied: ruamel.ordereddict; platform_python_implementation == "CPython" and python_version <= "2.7" in ./venv/lib/python2.7/site-packages (from ruamel.yaml>=0.11.10->vext>=0.5.21->vext.pyqt5->leap.bitmask==0.10a1)
Building wheels for collected packages: leap.bitmask-js
  Running setup.py bdist_wheel for leap.bitmask-js ... error
  Complete output from command /usr/home/lzhou/github.com/leapcode/bitmask-dev/archive/bitmask-dev-0.10a1/venv/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-L2mA96/leap.bitmask-js/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpWJbiXVpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/leap
  creating build/lib/leap/bitmask_js
  copying leap/bitmask_js/__init__.py -> build/lib/leap/bitmask_js
  creating build/lib/leap/bitmask_js/public
  copying leap/bitmask_js/public/app.bundle.js -> build/lib/leap/bitmask_js/public
  copying leap/bitmask_js/public/448c34a56d699c29117adc64c43affeb.woff2 -> build/lib/leap/bitmask_js/public
  copying leap/bitmask_js/public/fa2772327f55d8198301fdb8bcfc8158.woff -> build/lib/leap/bitmask_js/public
  error: can't copy 'leap/bitmask_js/public/js': doesn't exist or not a regular file
  
  ----------------------------------------
  Failed building wheel for leap.bitmask-js
  Running setup.py clean for leap.bitmask-js
Failed to build leap.bitmask-js
Installing collected packages: leap.bitmask-js, leap.bitmask
  Running setup.py install for leap.bitmask-js ... error
    Complete output from command /usr/home/lzhou/github.com/leapcode/bitmask-dev/archive/bitmask-dev-0.10a1/venv/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-L2mA96/leap.bitmask-js/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-TQUpoD-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/home/lzhou/github.com/leapcode/bitmask-dev/archive/bitmask-dev-0.10a1/venv/include/site/python2.7/leap.bitmask-js:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/leap
    creating build/lib/leap/bitmask_js
    copying leap/bitmask_js/__init__.py -> build/lib/leap/bitmask_js
    creating build/lib/leap/bitmask_js/public
    copying leap/bitmask_js/public/app.bundle.js -> build/lib/leap/bitmask_js/public
    copying leap/bitmask_js/public/448c34a56d699c29117adc64c43affeb.woff2 -> build/lib/leap/bitmask_js/public
    copying leap/bitmask_js/public/fa2772327f55d8198301fdb8bcfc8158.woff -> build/lib/leap/bitmask_js/public
    error: can't copy 'leap/bitmask_js/public/js': doesn't exist or not a regular file
    
    ----------------------------------------
Command "/usr/home/lzhou/github.com/leapcode/bitmask-dev/archive/bitmask-dev-0.10a1/venv/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-L2mA96/leap.bitmask-js/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-TQUpoD-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/home/lzhou/github.com/leapcode/bitmask-dev/archive/bitmask-dev-0.10a1/venv/include/site/python2.7/leap.bitmask-js" failed with error code 1 in /tmp/pip-build-L2mA96/leap.bitmask-js/
*** Error code 1

Stop.
make: stopped in /usr/home/lzhou/github.com/leapcode/bitmask-dev/archive/bitmask-dev-0.10a1

**Comment by meskio** [comment]
Nice, you are trying to build bitmask in freebsd? The VPN will require some work to integrate, as it has some linux-specific ways of launching openvpn. But email should work without much hand crafting.

We are about to close the issues in github, as we like to use our bugtracker for that: https://0xacab.org/leap/bitmask-dev/issues

Feel free to pass by irc (#leap @ irc.freenode.net) so we can explore your issues together or to create an issue in our bugtracker.
