### ISSUE TITLE
No providers are listed leads to 'Failed' and 'Unblock' message

### ISSUE THREAD

**Issue by marxistvegan** [leapcode/bitmask-dev#8]
Hey all, in the latest bitmask-dev build compiled locally or using the already compiled download no longer lists providers. When trying to configure the errors vary from json error that fails to load when using black.riseup.net as the url. The other when using riseup.net is the it loads but when trying to turnon it fails and has a button for 'Unblock' which does nothing when pressed. I am not sure what is blocked in this case, port maybe but not clear how to resolve.

System: Debian Buster/Testing

**Comment by micah** [comment]
Hi @marxistvegan - this was an error that crept in right before release. The newer versions (and the release version) do not have this issue. Can you try the newer version?

**Comment by meskio** [comment]
I belive this is solved in 0.10.1, if not feel free to open an issue in our bug tracker: https://0xacab.org/leap/bitmask-dev/issues
